# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "mycompany-terraform-state-shared-services"
    dynamodb_table = "shared-services-tfstate-lock-table"
    encrypt        = true
    key            = "mycompany/infrastructure-live/development/terraform.tfstate"
    profile        = "mycompany-shared-services-sso"
    region         = "us-east-2"
  }
}
